### ISSUE TITLE
team project issues

### ISSUE THREAD

**Issue by AhmadHaniShaheen** [AhmadHaniShaheen/team_project_quize#1]
## Todo

- [ ] #2
- [ ] Levels List. (List View Builder)
- [ ] Create Levels Object.
- [ ] Description Screen. (Receives Function & Level Object)
- [ ] Handle Timer.
- [ ] Choose the User Answer. (Disable Rest Buttons)
- [ ] Score Keeper.
- [ ] Alert Dialog.
